### ISSUE TITLE
Is this the new home for HippoMocks?

### ISSUE THREAD

**Issue by honggoff** [jeremy-ir/hippomocks#5]
Hello and thank you for working on HippoMocks!

Since the upstream repo seems unmaintained (no PRs merged and no answers to open issues) I was wondering if you are effectively taking over the project.

The background for my question is that I have some changes that would allow methods with argument using move semantics to be moked (See https://github.com/dascandy/hippomocks/issues/116). Would you be interested in PRs for such new features?

**Comment by jeremy-ir** [comment]
Sorry, I don't have email notifications enabled for this repo and I figured no one else was interested in it. Yes, I would absolutely be interested in ingesting changes you might have :)

I wouldn't say I'm taking over the project formally, but am interested in it for my own use.

**Comment by jeremy-ir** [comment]
Fixed in https://github.com/jeremy-ir/hippomocks/pull/8
